// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Printify.Infrastructure.Persistence;

#nullable disable

namespace Printify.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PrintifyDbContext))]
    [Migration("20260107080237_AddDocumentBytes")]
    partial class AddDocumentBytes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.Documents.DocumentElementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("CommandRaw")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("command_raw");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<int>("LengthInBytes")
                        .HasColumnType("INTEGER")
                        .HasColumnName("length_in_bytes");

                    b.Property<Guid?>("MediaId")
                        .HasColumnType("TEXT")
                        .HasColumnName("media_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.HasIndex("MediaId");

                    b.HasIndex("DocumentId", "Sequence")
                        .IsUnique();

                    b.ToTable("document_elements");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.Documents.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("BytesReceived")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bytes_received");

                    b.Property<int>("BytesSent")
                        .HasColumnType("INTEGER")
                        .HasColumnName("bytes_sent");

                    b.Property<string>("ClientAddress")
                        .HasColumnType("TEXT")
                        .HasColumnName("client_address");

                    b.Property<long>("CreatedAtUnixMs")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_at");

                    b.Property<int?>("HeightInDots")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height_in_dots");

                    b.Property<Guid>("PrintJobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("print_job_id");

                    b.Property<Guid>("PrinterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("printer_id");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("protocol");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.Property<int>("WidthInDots")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width_in_dots");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId", "CreatedAtUnixMs", "Id")
                        .HasDatabaseName("IX_documents_printer_created_at_id");

                    b.ToTable("documents");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.Documents.DocumentMediaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("checksum");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<long>("Length")
                        .HasColumnType("INTEGER")
                        .HasColumnName("length");

                    b.Property<Guid?>("OwnerWorkspaceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_workspace_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Checksum");

                    b.ToTable("document_media");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.PrinterJobs.PrintJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ClientAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("client_address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<int?>("HeightInDots")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height_in_dots");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("PrinterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("printer_id");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("protocol");

                    b.Property<int>("WidthInDots")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width_in_dots");

                    b.HasKey("Id");

                    b.ToTable("print_jobs");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.Printers.PrinterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedFromIp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_from_ip");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_pinned");

                    b.Property<DateTimeOffset?>("LastDocumentReceivedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_document_received_at");

                    b.Property<Guid?>("LastViewedDocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_viewed_document_id");

                    b.Property<Guid>("OwnerWorkspaceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_workspace_id");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.ToTable("printers");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.Printers.PrinterOperationalFlagsEntity", b =>
                {
                    b.Property<Guid>("PrinterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("printer_id");

                    b.Property<bool>("HasError")
                        .HasColumnType("INTEGER")
                        .HasColumnName("has_error");

                    b.Property<bool>("IsCoverOpen")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cover_open");

                    b.Property<bool>("IsOffline")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_offline");

                    b.Property<bool>("IsPaperNearEnd")
                        .HasColumnType("INTEGER")
                        .HasColumnName("paper_near_end");

                    b.Property<bool>("IsPaperOut")
                        .HasColumnType("INTEGER")
                        .HasColumnName("paper_out");

                    b.Property<string>("TargetState")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("target_state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("PrinterId");

                    b.ToTable("printer_operational_flags");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.Workspaces.WorkspaceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedFromIp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_from_ip");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_name");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.HasKey("Id");

                    b.ToTable("workspaces");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.Documents.DocumentElementEntity", b =>
                {
                    b.HasOne("Printify.Infrastructure.Persistence.Entities.Documents.DocumentEntity", "Document")
                        .WithMany("Elements")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Printify.Infrastructure.Persistence.Entities.Documents.DocumentMediaEntity", "Media")
                        .WithMany()
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Document");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.Printers.PrinterEntity", b =>
                {
                    b.OwnsOne("Printify.Infrastructure.Persistence.Entities.Printers.PrinterSettingsEntity", "Settings", b1 =>
                        {
                            b1.Property<Guid>("PrinterEntityId")
                                .HasColumnType("TEXT");

                            b1.Property<decimal?>("BufferDrainRate")
                                .HasColumnType("TEXT")
                                .HasColumnName("buffer_drain_rate");

                            b1.Property<int?>("BufferMaxCapacity")
                                .HasColumnType("INTEGER")
                                .HasColumnName("buffer_max_capacity");

                            b1.Property<bool>("EmulateBufferCapacity")
                                .HasColumnType("INTEGER")
                                .HasColumnName("emulate_buffer_capacity");

                            b1.Property<int?>("HeightInDots")
                                .HasColumnType("INTEGER")
                                .HasColumnName("height_in_dots");

                            b1.Property<int>("ListenTcpPortNumber")
                                .HasColumnType("INTEGER")
                                .HasColumnName("listen_tcp_port_number");

                            b1.Property<string>("Protocol")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("protocol");

                            b1.Property<int>("WidthInDots")
                                .HasColumnType("INTEGER")
                                .HasColumnName("width_in_dots");

                            b1.HasKey("PrinterEntityId");

                            b1.HasIndex("ListenTcpPortNumber")
                                .IsUnique();

                            b1.ToTable("printers");

                            b1.WithOwner()
                                .HasForeignKey("PrinterEntityId");
                        });

                    b.Navigation("Settings")
                        .IsRequired();
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.Printers.PrinterOperationalFlagsEntity", b =>
                {
                    b.HasOne("Printify.Infrastructure.Persistence.Entities.Printers.PrinterEntity", null)
                        .WithOne()
                        .HasForeignKey("Printify.Infrastructure.Persistence.Entities.Printers.PrinterOperationalFlagsEntity", "PrinterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.Documents.DocumentEntity", b =>
                {
                    b.Navigation("Elements");
                });
#pragma warning restore 612, 618
        }
    }
}
