// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Printify.Infrastructure.Persistence;

#nullable disable

namespace Printify.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PrintifyDbContext))]
    partial class PrintifyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.AnonymousSessions.AnonymousSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedFromIp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_from_ip");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_active_at");

                    b.Property<Guid?>("LinkedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("linked_user_id");

                    b.HasKey("Id");

                    b.HasIndex("LinkedUserId");

                    b.ToTable("anonymous_sessions");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.Users.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedFromIp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_from_ip");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.AnonymousSessions.AnonymousSessionEntity", b =>
                {
                    b.HasOne("Printify.Infrastructure.Persistence.Entities.Users.UserEntity", "LinkedUser")
                        .WithMany()
                        .HasForeignKey("LinkedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LinkedUser");
                });
#pragma warning restore 612, 618
        }
    }
}
