// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Printify.Infrastructure.Persistence;

#nullable disable

namespace Printify.Infrastructure.Migrations
{
    [DbContext(typeof(PrintifyDbContext))]
    partial class PrintifyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.AnonymousSessions.AnonymousSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedFromIp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_from_ip");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<DateTimeOffset>("LastActiveAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_active_at");

                    b.Property<Guid?>("LinkedUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("linked_user_id");

                    b.HasKey("Id");

                    b.HasIndex("LinkedUserId");

                    b.ToTable("anonymous_sessions");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.Documents.DocumentElementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_id");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("type");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("payload");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sequence");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId", "Sequence")
                        .IsUnique();

                    b.ToTable("document_elements");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.Documents.DocumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ClientAddress")
                        .HasColumnType("TEXT")
                        .HasColumnName("client_address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PrintJobId")
                        .HasColumnType("TEXT")
                        .HasColumnName("print_job_id");

                    b.Property<Guid>("PrinterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("printer_id");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("protocol");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("PrinterId", "CreatedAt", "Id")
                        .HasDatabaseName("IX_documents_printer_created_at_id");

                    b.ToTable("documents");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.Documents.DocumentMediaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .HasColumnType("TEXT")
                        .HasColumnName("checksum");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DocumentElementId")
                        .HasColumnType("TEXT")
                        .HasColumnName("document_element_id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<long?>("Length")
                        .HasColumnType("INTEGER")
                        .HasColumnName("length");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Checksum");

                    b.HasIndex("DocumentElementId")
                        .IsUnique();

                    b.ToTable("document_media");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.PrinterJobs.PrintJobEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ClientAddress")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("client_address");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<int?>("HeightInDots")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height_in_dots");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<Guid>("PrinterId")
                        .HasColumnType("TEXT")
                        .HasColumnName("printer_id");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("protocol");

                    b.Property<int>("WidthInDots")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width_in_dots");

                    b.HasKey("Id");

                    b.ToTable("print_jobs");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.Printers.PrinterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<decimal?>("BufferDrainRate")
                        .HasColumnType("TEXT")
                        .HasColumnName("buffer_drain_rate");

                    b.Property<int?>("BufferMaxCapacity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("buffer_max_capacity");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedFromIp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_from_ip");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("EmulateBufferCapacity")
                        .HasColumnType("INTEGER")
                        .HasColumnName("emulate_buffer_capacity");

                    b.Property<int?>("HeightInDots")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height_in_dots");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_pinned");

                    b.Property<int>("ListenTcpPortNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("listen_tcp_port_number");

                    b.Property<Guid?>("OwnerAnonymousSessionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_anonymous_session_id");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("protocol");

                    b.Property<int>("WidthInDots")
                        .HasColumnType("INTEGER")
                        .HasColumnName("width_in_dots");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.ToTable("printers");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.Users.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedFromIp")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_from_ip");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_deleted");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.AnonymousSessions.AnonymousSessionEntity", b =>
                {
                    b.HasOne("Printify.Infrastructure.Persistence.Entities.Users.UserEntity", "LinkedUser")
                        .WithMany()
                        .HasForeignKey("LinkedUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LinkedUser");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.Documents.DocumentElementEntity", b =>
                {
                    b.HasOne("Printify.Infrastructure.Persistence.Entities.Documents.DocumentEntity", "Document")
                        .WithMany("Elements")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.Documents.DocumentMediaEntity", b =>
                {
                    b.HasOne("Printify.Infrastructure.Persistence.Entities.Documents.DocumentElementEntity", "Element")
                        .WithOne("Media")
                        .HasForeignKey("Printify.Infrastructure.Persistence.Entities.Documents.DocumentMediaEntity", "DocumentElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.Documents.DocumentElementEntity", b =>
                {
                    b.Navigation("Media");
                });

            modelBuilder.Entity("Printify.Infrastructure.Persistence.Entities.Documents.DocumentEntity", b =>
                {
                    b.Navigation("Elements");
                });
#pragma warning restore 612, 618
        }
    }
}
